apiVersion: nais.io/v1alpha1
kind: Application
metadata:
    name: promstatusproxy
    namespace: navdig
    labels:
        team: navdig
spec:
    image: {{ image }}
    port: 8080
    env:
        - name: TENANT
          value: nav.no
        - name: ENV
          value: dev
    ingresses:
        - https://promstatusproxy.dev.nav.no
    azure:
        application:
            tenant: nav.no
            enabled: true

    accessPolicy:
        outbound:
            rules:
                - application: portalserver
                  namespace: navdig
                  cluster: dev-gcp

