apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: promstatusproxy
  namespace: navdig
  labels:
    team: navdig
spec:
  image: {{ image }}
  port: 8080
  env:
    - name: portalserver_path
      value: "http://portalserver"
    - name: TENANT
      value: nav.no
    - name: ENV
      value: prod
  ingresses:
    - https://promstatusproxy.intern.nav.no
  azure:
    application:
      tenant: nav.no
      enabled: true

  accessPolicy:
    outbound:
      rules:
        - application: portalserver