apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: promstatusproxy
  namespace: navdig
  labels:
    team: navdig
spec:
  image: {{ image }}
  port: 8080
  env:
    - name: portalserver_path
      value: "http://portalserver"
  ingresses:
    - https://promstatusproxy.intern.nav.no
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: portalserver
          namespace: navdig
          cluster: prod-gcp


